name: run main.py

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install microsoft word 
        run: choco install microsoft-office-deployment

      - name: execute py script # run main.py
        run: python main.py
